version: "3"
services:
  vault:
    container_name: vault
    image: ghcr.io/bushido-games/vault:1.0.0
    command: vault server -config /vault/config/config.hlc
    restart: always
    volumes:
      - vault-volume:/vault/file
    environment:
      VAULT_API_ADDR: http://0.0.0.0:8200
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
volumes:
  vault-volume:
