name: Create pkg

on:
  workflow_call:
    inputs:
      pkg-name:
        required: true
        type: string
    secrets:
      SUBMODULE_DEPLOY_KEY:
        required: true

env:
  REGISTRY: ghcr.io
  ORGANIZATION: bushido-games

jobs:
  create-pkg:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup SSH keys
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SUBMODULE_DEPLOY_KEY }}

      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Yarn install
        run: yarn install

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ inputs.pkg-name }} package
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ inputs.pkg-name }}:${{ steps.package-version.outputs.current-version}}
